import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Heading } from '@chakra-ui/react'
import React from "react";
import Searcher from '../components/searcher'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading  fontSize={'2xl'}>내가 만들려고 만든 영단어 사이트.</Heading>
        <Heading mb = '5' as='h1' size='4xl'>Synonym</Heading>
        <Searcher placeholder = 'Write the word'/>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/rnaudah"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by{' '}Rnaudah
        </a>
      </footer>
    </div>
  )
}

